services:
  - type: static
    name: frontend
    plan: starter
    buildCommand: "npm install && npm run build"
    staticPublishPath: "build"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://server-dev-quzm.onrender.com" 
    branch: main
