version: '3'
services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    platform: linux/amd64
    environment:
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: dbPassword
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: your-username/managementapp:latest
    ports:
      - "3000:3000"
    environment:
      DB_USER: dbUser
      DB_PASSWORD: dbPassword
      DB_HOST: dbHost
      DB_DATABASE: db
    depends_on:
      - db

 
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  postgres_data:
