
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ndeye650/frontend:latest
    platform: linux/amd64
    ports:
      - "80:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: ndeye650/server:latest
    platform: linux/amd64
    ports:
      - "3080:3080"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://dbUser:dbPassword@db:5432/db