
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ndeye650/frontend:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: ndeye650/server:latest
    platform: linux/amd64
    ports:
      - "3080:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://dbUser:dbPassword@db:5432/db
    depends_on:
      - db          
      
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: dbPassword
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
