version: '3'
services:

  db:
    image: postgres
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=dbPassword
      - POSTGRES_USER=dbUser
      - POSTGRES_DB=db
    volumes:
      - managementapp:/data/db

  client:
    depends_on: 
      - server
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - VITE_URL=http://localhost:8000
    volumes:
      - ./client:/app

  server:
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment: 
      - DBUSER=dbUser
      - DBHOST=db 
      - DB=db
      - DBPASSWORD=dbPassword
      - DBPORT=5432
    volumes:
      - ./server:/app

volumes:
  managementapp:
