services:
  - type: web
    name: server
    env: node
    plan: starter 
    buildCommand: "npm install && npm start" 
    startCommand: "npm run dev"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: managementapp
          property: connectionString
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: "/health" 
    branch: main 

  - type: web
    name: frontend
    plan: starter
    buildCommand: "npm install && npm run build"
    staticPublishPath: "build"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://server-dev-quzm.onrender.com" 
    branch: main

  - type: postgresql
    name: management
    plan: starter
    ipAllowList: 
      - "0.0.0.0/0" 
