-- managementapp=# \d users
--                                           Table "public.users"
--   Column   |            Type             | Collation | Nullable |                Default                
-- -----------+-----------------------------+-----------+----------+---------------------------------------
--  userid    | integer                     |           | not null | nextval('users_userid_seq'::regclass)
--  username  | character varying(100)      |           | not null | 
--  email     | character varying(100)      |           | not null | 
--  password  | character varying(255)      |           | not null | 
--  role      | user_role                   |           | not null | 
--  createdat | timestamp without time zone |           |          | CURRENT_TIMESTAMP
-- Indexes:
--     "users_pkey" PRIMARY KEY, btree (userid)
--     "users_email_key" UNIQUE CONSTRAINT, btree (email)
-- Referenced by:
--     TABLE "enrollments" CONSTRAINT "enrollments_userid_fkey" FOREIGN KEY (userid) REFERENCES users(userid)
--     TABLE "results" CONSTRAINT "results_userid_fkey" FOREIGN KEY (userid) REFERENCES users(userid)

-- managementapp=# \d course
-- Did not find any relation named "course".
-- managementapp=# \d courses
--                                             Table "public.courses"
--    Column    |            Type             | Collation | Nullable |                  Default                  
-- -------------+-----------------------------+-----------+----------+-------------------------------------------
--  courseid    | integer                     |           | not null | nextval('courses_courseid_seq'::regclass)
--  coursename  | character varying(100)      |           | not null | 
--  description | text                        |           |          | 
--  createdat   | timestamp without time zone |           |          | CURRENT_TIMESTAMP
-- Indexes:
--     "courses_pkey" PRIMARY KEY, btree (courseid)
-- Referenced by:
--     TABLE "enrollments" CONSTRAINT "enrollments_courseid_fkey" FOREIGN KEY (courseid) REFERENCES courses(courseid)
--     TABLE "modules" CONSTRAINT "modules_courseid_fkey" FOREIGN KEY (courseid) REFERENCES courses(courseid)

-- managementapp=# \d modules
--                                            Table "public.modules"
--    Column   |            Type             | Collation | Nullable |                  Default                  
-- ------------+-----------------------------+-----------+----------+-------------------------------------------
--  moduleid   | integer                     |           | not null | nextval('modules_moduleid_seq'::regclass)
--  courseid   | integer                     |           |          | 
--  modulename | character varying(100)      |           | not null | 
--  createdat  | timestamp without time zone |           |          | CURRENT_TIMESTAMP
-- Indexes:
--     "modules_pkey" PRIMARY KEY, btree (moduleid)
-- Foreign-key constraints:
--     "modules_courseid_fkey" FOREIGN KEY (courseid) REFERENCES courses(courseid)
-- Referenced by:
--     TABLE "coursecontent" CONSTRAINT "coursecontent_moduleid_fkey" FOREIGN KEY (moduleid) REFERENCES modules(moduleid)
--     TABLE "quizzes" CONSTRAINT "quizzes_moduleid_fkey" FOREIGN KEY (moduleid) REFERENCES modules(moduleid)

-- managementapp=# \d coursecontent
--                                              Table "public.coursecontent"
--     Column    |            Type             | Collation | Nullable |                     Default                      
-- --------------+-----------------------------+-----------+----------+--------------------------------------------------
--  contentid    | integer                     |           | not null | nextval('coursecontent_contentid_seq'::regclass)
--  moduleid     | integer                     |           |          | 
--  contenttype  | character varying(50)       |           | not null | 
--  contenttitle | character varying(100)      |           |          | 
--  contenturl   | text                        |           |          | 
--  createdat    | timestamp without time zone |           |          | CURRENT_TIMESTAMP
-- Indexes:
--     "coursecontent_pkey" PRIMARY KEY, btree (contentid)
-- Foreign-key constraints:
--     "coursecontent_moduleid_fkey" FOREIGN KEY (moduleid) REFERENCES modules(moduleid)

-- managementapp=# \d quizzes
--                                            Table "public.quizzes"
--    Column    |            Type             | Collation | Nullable |                 Default                 
-- -------------+-----------------------------+-----------+----------+-----------------------------------------
--  quizid      | integer                     |           | not null | nextval('quizzes_quizid_seq'::regclass)
--  moduleid    | integer                     |           |          | 
--  quizname    | character varying(100)      |           | not null | 
--  description | text                        |           |          | 
--  totalmarks  | integer                     |           | not null | 
--  createdat   | timestamp without time zone |           |          | CURRENT_TIMESTAMP
-- Indexes:
--     "quizzes_pkey" PRIMARY KEY, btree (quizid)
-- Foreign-key constraints:
--     "quizzes_moduleid_fkey" FOREIGN KEY (moduleid) REFERENCES modules(moduleid)
-- Referenced by:
--     TABLE "results" CONSTRAINT "results_quizid_fkey" FOREIGN KEY (quizid) REFERENCES quizzes(quizid)

-- managementapp=# \d quizzesr

-- managementapp=# \d results
--                                              Table "public.results"
--      Column     |            Type             | Collation | Nullable |                  Default                  
-- ----------------+-----------------------------+-----------+----------+-------------------------------------------
--  resultid       | integer                     |           | not null | nextval('results_resultid_seq'::regclass)
--  userid         | integer                     |           |          | 
--  quizid         | integer                     |           |          | 
--  score          | integer                     |           |          | 
--  completiondate | timestamp without time zone |           |          | CURRENT_TIMESTAMP
-- Indexes:
--     "results_pkey" PRIMARY KEY, btree (resultid)
-- Foreign-key constraints:
--     "results_quizid_fkey" FOREIGN KEY (quizid) REFERENCES quizzes(quizid)
--     "results_userid_fkey" FOREIGN KEY (userid) REFERENCES users(userid)

-- managementapp=# \d enrollments
--                                                Table "public.enrollments"
--      Column     |            Type             | Collation | Nullable |                      Default                      
-- ----------------+-----------------------------+-----------+----------+---------------------------------------------------
--  enrollmentid   | integer                     |           | not null | nextval('enrollments_enrollmentid_seq'::regclass)
--  userid         | integer                     |           |          | 
--  courseid       | integer                     |           |          | 
--  enrollmentdate | timestamp without time zone |           |          | CURRENT_TIMESTAMP
-- Indexes:
--     "enrollments_pkey" PRIMARY KEY, btree (enrollmentid)
-- Foreign-key constraints:
--     "enrollments_courseid_fkey" FOREIGN KEY (courseid) REFERENCES courses(courseid)
--     "enrollments_userid_fkey" FOREIGN KEY (userid) REFERENCES users(userid)

-- managementapp=# 
