services:
  - type: web
    name: server
    env: node
    plan: starter 
    buildCommand: "npm install && npm run start" 
    startCommand: "npm run dev"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: managementapp
          property: connectionString
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: "/health" 
    branch: main 

<<<<<<< HEAD:server/render.yaml
  # - type: static
  #   name: frontend
  #   plan: starter
  #   buildCommand: "npm install && npm run build"
  #   staticPublishPath: "build"
  #   envVars:
  #     - key: REACT_APP_API_URL
  #       value: "https://server-dev-quzm.onrender.com" 
  #   branch: main

  # - type: postgresql
=======
  - type: web
    name: frontend
    plan: starter
    buildCommand: "npm install && npm run build"
    staticPublishPath: "build"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://server-dev-quzm.onrender.com" 
    branch: main

  # - type: database
>>>>>>> d77d92545e6fb6b5bf4c4dccf67106312f99ef24:render.yaml
  #   name: management
  #   plan: starter
  #   ipAllowList: 
  #     - "0.0.0.0/0" 
